apiVersion: apps/v1
kind: Deployment
metadata:
  name: stolon-sentinel
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stolon-sentinel
  template:
    metadata:
      labels:
        app: stolon-sentinel 
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: stolon-sentinel
          image: shishirkhandelwal/stolon:pg12
          command:
          - "/bin/bash"
          - "-ec"
          - "exec gosu stolon stolon-sentinel"
          env:
          - name: STSENTINEL_CLUSTER_NAME
            value: "stolon"
          - name: STSENTINEL_LOG_COLOR
            value: "true"
          - name: STSENTINEL_LOG_LEVEL
            value: "debug"
          - name: STSENTINEL_METRICS_LISTEN_ADDR
            value: "0.0.0.0:8080"
          - name: STSENTINEL_STORE_BACKEND
            value: "consul"
          - name: STSENTINEL_STORE_ENDPOINTS
            value: "consul-consul-ui:80"
          ports:
            - containerPort: 8080
